
INSERT INTO customer(CUSTOMER_CODE, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_PINCODE, CUSTOMER_EMAIL, CONTACT_NUMBER, REGISTRATION_DATE, CREATED_BY, MODIFIED_DATE)
VALUES ('123','nsbt','lkjasdf','564231','ksjdfh@gmail.com','9876543210','24/08/1996','charan','24/08/1996');

CREATE TABLE customer (
  CUSTOMER_CODE number(10) NOT NULL,
  CUSTOMER_NAME varchar(30) NOT NULL,
  CUSTOMER_ADDRESS varchar(100) NOT NULL,
  CUSTOMER_PINCODE varchar(6) NOT NULL,
    CUSTOMER_EMAIL varchar(100) NOT NULL,
  CONTACT_NUMBER varchar(20) DEFAULT NULL,
  REGISTRATION_DATE date NOT NULL,
  CREATED_BY varchar(30) NOT NULL,
  MODIFIED_DATE date DEFAULT NULL,
  PRIMARY KEY (CUSTOMER_CODE)
)



INSERT INTO customer(CUSTOMER_CODE, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_PINCODE, CUSTOMER_EMAIL, CONTACT_NUMBER, REGISTRATION_DATE, CREATED_BY, MODIFIED_DATE)
VALUES ('123','nsbt','lkjasdf','564231','ksjdfh@gmail.com','9876543210','24/08/1996','charan','24/08/1996');


INSERT INTO customer(CUSTOMER_CODE, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_PINCODE, CUSTOMER_EMAIL, CONTACT_NUMBER, REGISTRATION_DATE, CREATED_BY, MODIFIED_DATE)
VALUES (2,'charan','kavali','524201','charan@gmail.com','9542634566','24/08/1996','charan','24/08/1996');
